### ISSUE TITLE
npm start crashes

### ISSUE THREAD

**Issue by trium4** [ceolter/ag-grid-ng2-example#34] opened 2017-01-15 17:26 UTC
Hello,
your current angular-cli example crashes for me on Win10/64Bit.

Do you have any solution for me?
Many thanks.
@trium4
[npm-debug.log.txt](https://github.com/ceolter/ag-grid-ng2-example/files/706760/npm-debug.log.txt)
[mylog.stdout.txt](https://github.com/ceolter/ag-grid-ng2-example/files/706761/mylog.stdout.txt)
[mylog.stderr.txt](https://github.com/ceolter/ag-grid-ng2-example/files/706762/mylog.stderr.txt)

**Comment by seanlandsman** [comment] 2017-01-17 15:12
hi - we can't reproduce this here, on either osx or windows 10.

Have you installed all the npm dependencies?

**Comment by seanlandsman** [comment] 2017-01-19 08:15
Closing as cannot reproduce

**Closed by seanlandsman** 2017-01-19 08:15 UTC
Labels: needs_repro
